# Generated by Django 4.2.2 on 2024-11-04 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        help_text="при наличии",
                        max_length=100,
                        null=True,
                        verbose_name="ФИО",
                    ),
                ),
                (
                    "email_client",
                    models.EmailField(
                        help_text="обязательно",
                        max_length=254,
                        unique=True,
                        verbose_name="электронная почта",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец клиента",
                    ),
                ),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ("email_client",),
            },
        ),
        migrations.CreateModel(
            name="Letter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Рассылка",
                        help_text="Введите заголовок",
                        max_length=100,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Введите текс", verbose_name="Сообщение"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Введите владельца",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="активность рассылки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время создания рассылки"
                    ),
                ),
                (
                    "send_time",
                    models.DateTimeField(verbose_name="дата и время отправки рассылки"),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("D", "Раз в день"),
                            ("W", "Раз в неделю"),
                            ("M", "Раз в месяц"),
                        ],
                        default="W",
                        max_length=1,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CR", "Создана"), ("RN", "Запущена")],
                        default="CR",
                        max_length=2,
                        verbose_name="статус",
                    ),
                ),
                (
                    "clients",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="clients",
                        to="mailing.client",
                        verbose_name="клиенты",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mailings",
                        to="mailing.letter",
                        verbose_name="сообщения",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ("-created_at",),
                "permissions": [
                    ("disable_mailing", "Может делать рассылку неактивной")
                ],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время попытки отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SC", "Успешно"), ("FL", "Неуспешно")],
                        max_length=2,
                        verbose_name="статус попытки",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailing.mailing",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
                "ordering": ["-attempt_time"],
            },
        ),
    ]
