# Generated by Django 4.2.2 on 2024-11-03 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mail",
            old_name="clienty",
            new_name="clients",
        ),
    ]
