# Generated by Django 4.2.2 on 2024-11-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                help_text="при наличии", max_length=100, verbose_name="ФИО"
            ),
        ),
    ]
