# Generated by Django 4.2.2 on 2024-11-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_client_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="clients",
                to="mailing.client",
                verbose_name="клиенты",
            ),
        ),
    ]
