# Generated by Django 4.2.2 on 2024-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_mailing_alter_letter_options_remove_client_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="clients",
                to="mailing.client",
                verbose_name="клиенты",
            ),
        ),
    ]
