# Generated by Django 4.2.2 on 2024-11-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email_client",
            field=models.EmailField(
                help_text="Обязательно",
                max_length=254,
                unique=True,
                verbose_name="электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                help_text="Обязательно", max_length=100, verbose_name="ФИО"
            ),
        ),
    ]
