# Generated by Django 4.2.2 on 2024-11-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_alter_mailing_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email_client",
            field=models.EmailField(
                help_text="обязательно",
                max_length=254,
                unique=True,
                verbose_name="электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(
                blank=True,
                help_text="при наличии",
                max_length=100,
                null=True,
                verbose_name="ФИО",
            ),
        ),
    ]
