# Generated by Django 4.2.2 on 2024-11-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_client_email_client_alter_client_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingJob",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("job_id", models.CharField(max_length=255, unique=True)),
                ("next_run_time", models.DateTimeField(null=True)),
                ("trigger", models.CharField(max_length=50)),
                ("args", models.JSONField(null=True)),
                ("kwargs", models.JSONField(null=True)),
                ("job_state", models.JSONField(null=True)),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="mailing.mailing",
                    ),
                ),
            ],
        ),
    ]
