# Generated by Django 4.2.2 on 2024-11-03 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_mailingjob"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingjob",
            options={
                "ordering": ["-next_run_time"],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                related_name="clients",
                to="mailing.client",
                verbose_name="клиенты",
            ),
        ),
        migrations.AlterField(
            model_name="mailingjob",
            name="args",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailingjob",
            name="job_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailingjob",
            name="kwargs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailingjob",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="mailing.mailing",
                verbose_name="рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="mailingjob",
            name="next_run_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
