# Generated by Django 4.2.2 on 2024-11-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailingjob_options_alter_mailing_clients_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingjob",
            options={
                "ordering": ["-mailing"],
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
            },
        ),
        migrations.AddField(
            model_name="mailingjob",
            name="status",
            field=models.CharField(
                choices=[("SC", "Успешно"), ("FL", "Неуспешно")],
                default="SC",
                max_length=2,
                verbose_name="статус попытки",
            ),
        ),
    ]
