# Generated by Django 4.2.2 on 2024-11-03 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailingjob_options_mailingjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingjob",
            name="attempt_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="время попытки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mailingjob",
            name="server_response",
            field=models.TextField(
                blank=True, null=True, verbose_name="ответ почтового сервера"
            ),
        ),
    ]
